version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: aurora-postgres
    environment:
      POSTGRES_USER: aurora
      POSTGRES_PASSWORD: aurora_dev_password
      POSTGRES_DB: aurora_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 