// Demo data for TransactionTable component
// Use in Storybook or when showDemoData prop is true

import type { Transaction } from './TransactionTable';

export const demoTransactions: Transaction[] = [
  {
    id: '1',
    date: '06/2025',
    prism: 'bitcoin Pizza',
    prismId: 'bitcoin-pizza',
    amount: '$1,250.00',
    status: 'Successful',
    account: 'Jamie Smith',
    accountId: 'jamie-smith',
    isFavorite: false,
  },
  {
    id: '2',
    date: '07/2025',
    prism: 'Crypto Feast',
    prismId: 'crypto-feast',
    amount: '$500.00',
    status: 'Pending',
    account: 'Alex Johnson',
    accountId: 'alex-johnson',
    isFavorite: false,
  },
  {
    id: '3',
    date: '09/2025',
    prism: 'Tech Summit',
    prismId: 'tech-summit',
    amount: '225078764578.00 sats',
    status: 'Successful',
    account: 'QHFI8WE8DYHWEBJhbsbdcus...',
    accountId: 'user-3',
    isFavorite: true,
  },
  {
    id: '4',
    date: '11/2025',
    prism: 'Health Expo',
    prismId: 'health-expo',
    amount: '3000.00 Sats',
    status: 'Active',
    account: 'Michael Brown',
    accountId: 'michael-brown',
    isFavorite: false,
  },
  {
    id: '5',
    date: '06/2024',
    prism: 'The true man show movie...',
    prismId: 'true-man-show',
    amount: '999999999999999 Sats',
    status: 'Active',
    account: 'user@example.com',
    accountId: 'user-5',
    isFavorite: false,
  },
  {
    id: '6',
    date: '04/2025',
    prism: 'Fashion Week',
    prismId: 'fashion-week',
    amount: '56.5643679 Sats',
    status: 'Successful',
    account: 'Jessica Lee',
    accountId: 'jessica-lee',
    isFavorite: false,
  },
  {
    id: '7',
    date: '08/2025',
    prism: 'Food Festival',
    prismId: 'food-festival',
    amount: '1 Btc',
    status: 'Successful',
    account: 'kcuabcjbau2e482r982hufwueff...',
    accountId: 'user-7',
    isFavorite: false,
  },
  {
    id: '8',
    date: '12/2025',
    prism: 'Finance Forum',
    prismId: 'finance-forum',
    amount: '$1,200.00',
    status: 'Pending',
    account: 'Rachel Adams',
    accountId: 'rachel-adams',
    isFavorite: false,
  },
];
